package com.rrh.mapper.group;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.rrh.model.group.TbFriend;

public interface TbFriendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    int deleteByPrimaryKey(@Param("friendId") String friendId, @Param("userId") String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    int insert(TbFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    TbFriend selectByPrimaryKey(@Param("friendId") String friendId, @Param("userId") String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    List<TbFriend> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    int updateByPrimaryKey(TbFriend record);
}