package com.rrh.mapper.group;

import java.util.List;

import com.rrh.model.group.TbGroup;

public interface TbGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_group
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    int deleteByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_group
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    int insert(TbGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_group
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    TbGroup selectByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_group
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    List<TbGroup> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_group
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    int updateByPrimaryKey(TbGroup record);
}