package com.rrh.mapper.group;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.rrh.common.mybatis.bean.GroupListBean;
import com.rrh.model.group.TbGroup;

public interface TbGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_group
     *
     * @mbggenerated Wed Nov 25 14:34:45 CST 2015
     */
    int deleteByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_group
     *
     * @mbggenerated Wed Nov 25 14:34:45 CST 2015
     */
    int insert(TbGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_group
     *
     * @mbggenerated Wed Nov 25 14:34:45 CST 2015
     */
    TbGroup selectByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_group
     *
     * @mbggenerated Wed Nov 25 14:34:45 CST 2015
     */
    List<TbGroup> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_group
     *
     * @mbggenerated Wed Nov 25 14:34:45 CST 2015
     */
    int updateByPrimaryKey(TbGroup record);
    
    /**查询我的普通群列表*/
    public List<GroupListBean> findGroupList(@Param(value="userId") int userId);
    /**查询认证群和副群列表*/
    public List<GroupListBean> findGroupAuthList(@Param(value="userId") int userId);
    
}