package com.rrh.mapper.order;

import java.util.List;

import com.rrh.model.order.TbOrderPic;

public interface TbOrderPicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_pic
     *
     * @mbggenerated Wed Nov 25 14:33:18 CST 2015
     */
    int deleteByPrimaryKey(Integer picId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_pic
     *
     * @mbggenerated Wed Nov 25 14:33:18 CST 2015
     */
    int insert(TbOrderPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_pic
     *
     * @mbggenerated Wed Nov 25 14:33:18 CST 2015
     */
    TbOrderPic selectByPrimaryKey(Integer picId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_pic
     *
     * @mbggenerated Wed Nov 25 14:33:18 CST 2015
     */
    List<TbOrderPic> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_pic
     *
     * @mbggenerated Wed Nov 25 14:33:18 CST 2015
     */
    int updateByPrimaryKey(TbOrderPic record);
}