package com.rrh.mapper.order;

import java.util.List;

import com.rrh.model.order.TbOrderinfo;

public interface TbOrderinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orderinfo
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orderinfo
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    int insert(TbOrderinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orderinfo
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    TbOrderinfo selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orderinfo
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    List<TbOrderinfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orderinfo
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    int updateByPrimaryKey(TbOrderinfo record);
}