package com.rrh.mapper.business;

import java.util.List;

import com.rrh.model.business.TbBusinessTaskComment;

public interface TbBusinessTaskCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_task_comment
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int deleteByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_task_comment
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int insert(TbBusinessTaskComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_task_comment
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    TbBusinessTaskComment selectByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_task_comment
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    List<TbBusinessTaskComment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_task_comment
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int updateByPrimaryKey(TbBusinessTaskComment record);
}