package com.rrh.mapper.business;

import java.util.List;

import com.rrh.model.business.TbBusinessGoods;

public interface TbBusinessGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_goods
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int deleteByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_goods
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int insert(TbBusinessGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_goods
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    TbBusinessGoods selectByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_goods
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    List<TbBusinessGoods> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_goods
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int updateByPrimaryKey(TbBusinessGoods record);
}