package com.rrh.mapper.business;

import java.util.List;

import com.rrh.model.business.TbBusinessKnowledgeAttachment;

public interface TbBusinessKnowledgeAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_knowledge_attachment
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int deleteByPrimaryKey(Integer attachmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_knowledge_attachment
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int insert(TbBusinessKnowledgeAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_knowledge_attachment
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    TbBusinessKnowledgeAttachment selectByPrimaryKey(Integer attachmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_knowledge_attachment
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    List<TbBusinessKnowledgeAttachment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_knowledge_attachment
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int updateByPrimaryKey(TbBusinessKnowledgeAttachment record);
}