package com.rrh.mapper.business;

import java.util.List;

import com.rrh.model.business.TbBusinessKnowledgePraise;

public interface TbBusinessKnowledgePraiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_knowledge_praise
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int deleteByPrimaryKey(Integer praiseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_knowledge_praise
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int insert(TbBusinessKnowledgePraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_knowledge_praise
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    TbBusinessKnowledgePraise selectByPrimaryKey(Integer praiseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_knowledge_praise
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    List<TbBusinessKnowledgePraise> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_knowledge_praise
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int updateByPrimaryKey(TbBusinessKnowledgePraise record);
}