package com.rrh.mapper.business;

import java.util.List;

import com.rrh.model.business.TbBusinessTaskExecute;

public interface TbBusinessTaskExecuteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_task_execute
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int deleteByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_task_execute
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int insert(TbBusinessTaskExecute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_task_execute
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    TbBusinessTaskExecute selectByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_task_execute
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    List<TbBusinessTaskExecute> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_task_execute
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int updateByPrimaryKey(TbBusinessTaskExecute record);
}