package com.rrh.mapper.business;

import java.util.List;

import com.rrh.model.business.TbBusinessDep;

public interface TbBusinessDepMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_dep
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int deleteByPrimaryKey(Integer depId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_dep
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int insert(TbBusinessDep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_dep
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    TbBusinessDep selectByPrimaryKey(Integer depId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_dep
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    List<TbBusinessDep> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_dep
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int updateByPrimaryKey(TbBusinessDep record);
}