package com.rrh.mapper.business;

import java.util.List;

import com.rrh.model.business.TbBusinessTradeinfo;

public interface TbBusinessTradeinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_tradeinfo
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int deleteByPrimaryKey(Integer tradeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_tradeinfo
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int insert(TbBusinessTradeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_tradeinfo
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    TbBusinessTradeinfo selectByPrimaryKey(Integer tradeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_tradeinfo
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    List<TbBusinessTradeinfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_tradeinfo
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int updateByPrimaryKey(TbBusinessTradeinfo record);
}