package com.rrh.mapper.business;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.rrh.mobile.bean.req.BusinessCreateTeamRequest;
import com.rrh.model.business.TbBusiness;

public interface TbBusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int deleteByPrimaryKey(Integer businessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int insert(TbBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    TbBusiness selectByPrimaryKey(Integer businessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    List<TbBusiness> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int updateByPrimaryKey(TbBusiness record);
    
    //创建团队
    public int insertCreateTeam(BusinessCreateTeamRequest groupTeam);
    //获取团队信息
    public TbBusiness getByUserID(@Param(value="userId") int userId);
}