package com.rrh.mapper.business;

import java.util.List;

import com.rrh.model.business.TbBusinessWhiteboardsSendRecord;

public interface TbBusinessWhiteboardsSendRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_whiteboards_send_record
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int deleteByPrimaryKey(Integer wbId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_whiteboards_send_record
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int insert(TbBusinessWhiteboardsSendRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_whiteboards_send_record
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    TbBusinessWhiteboardsSendRecord selectByPrimaryKey(Integer wbId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_whiteboards_send_record
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    List<TbBusinessWhiteboardsSendRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_whiteboards_send_record
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int updateByPrimaryKey(TbBusinessWhiteboardsSendRecord record);
}