package com.rrh.mapper.business;

import java.util.List;

import com.rrh.model.business.TbBusinessPic;

public interface TbBusinessPicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_pic
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int deleteByPrimaryKey(Integer picId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_pic
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int insert(TbBusinessPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_pic
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    TbBusinessPic selectByPrimaryKey(Integer picId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_pic
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    List<TbBusinessPic> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_pic
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int updateByPrimaryKey(TbBusinessPic record);
}