package com.rrh.mapper.business;

import java.util.List;

import com.rrh.model.business.TbBusinessGoodsPic;

public interface TbBusinessGoodsPicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_goods_pic
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int deleteByPrimaryKey(Integer picId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_goods_pic
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int insert(TbBusinessGoodsPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_goods_pic
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    TbBusinessGoodsPic selectByPrimaryKey(Integer picId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_goods_pic
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    List<TbBusinessGoodsPic> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_goods_pic
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int updateByPrimaryKey(TbBusinessGoodsPic record);
}