package com.rrh.mapper.business;

import java.util.List;

import com.rrh.model.business.TbBusinessTaskPic;

public interface TbBusinessTaskPicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_task_pic
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int deleteByPrimaryKey(Integer picId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_task_pic
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int insert(TbBusinessTaskPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_task_pic
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    TbBusinessTaskPic selectByPrimaryKey(Integer picId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_task_pic
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    List<TbBusinessTaskPic> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_task_pic
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int updateByPrimaryKey(TbBusinessTaskPic record);
}