package com.rrh.mapper.business;

import java.util.List;

import com.rrh.model.business.TbBusinessWhiteboardsComment;

public interface TbBusinessWhiteboardsCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_whiteboards_comment
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int deleteByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_whiteboards_comment
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int insert(TbBusinessWhiteboardsComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_whiteboards_comment
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    TbBusinessWhiteboardsComment selectByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_whiteboards_comment
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    List<TbBusinessWhiteboardsComment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_whiteboards_comment
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    int updateByPrimaryKey(TbBusinessWhiteboardsComment record);
}