package com.rrh.mapper.business;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.rrh.model.business.TbBusinessTaskExecute;

public interface TbBusinessTaskExecuteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_task_execute
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("taskId") Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_task_execute
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int insert(TbBusinessTaskExecute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_task_execute
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    TbBusinessTaskExecute selectByPrimaryKey(@Param("userId") Integer userId, @Param("taskId") Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_task_execute
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    List<TbBusinessTaskExecute> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_business_task_execute
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int updateByPrimaryKey(TbBusinessTaskExecute record);
}