package com.rrh.mapper.business;

import java.util.List;

import com.rrh.model.business.TbDep;

public interface TbDepMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dep
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int deleteByPrimaryKey(Integer depId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dep
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int insert(TbDep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dep
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    TbDep selectByPrimaryKey(Integer depId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dep
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    List<TbDep> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dep
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int updateByPrimaryKey(TbDep record);
}