package com.rrh.mapper.business;

import java.util.List;

import com.rrh.model.business.TbKnowledgeAttachment;

public interface TbKnowledgeAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_knowledge_attachment
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int deleteByPrimaryKey(Integer attachmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_knowledge_attachment
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int insert(TbKnowledgeAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_knowledge_attachment
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    TbKnowledgeAttachment selectByPrimaryKey(Integer attachmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_knowledge_attachment
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    List<TbKnowledgeAttachment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_knowledge_attachment
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int updateByPrimaryKey(TbKnowledgeAttachment record);
}