package com.rrh.mapper.business;

import java.util.List;

import com.rrh.model.business.TbPraise;

public interface TbPraiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_praise
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int deleteByPrimaryKey(Integer praiseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_praise
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int insert(TbPraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_praise
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    TbPraise selectByPrimaryKey(Integer praiseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_praise
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    List<TbPraise> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_praise
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int updateByPrimaryKey(TbPraise record);
}