package com.rrh.mapper.business;

import java.util.List;

import com.rrh.model.business.TbTaskPic;

public interface TbTaskPicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_pic
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int deleteByPrimaryKey(Integer picId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_pic
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int insert(TbTaskPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_pic
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    TbTaskPic selectByPrimaryKey(Integer picId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_pic
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    List<TbTaskPic> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_pic
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int updateByPrimaryKey(TbTaskPic record);
}