package com.rrh.mapper.business;

import java.util.List;

import com.rrh.model.business.TbTaskComment;

public interface TbTaskCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_comment
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int deleteByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_comment
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int insert(TbTaskComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_comment
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    TbTaskComment selectByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_comment
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    List<TbTaskComment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_comment
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int updateByPrimaryKey(TbTaskComment record);
}