package com.rrh.mapper.business;

import java.util.List;

import com.rrh.model.business.TbTradeinfo;

public interface TbTradeinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tradeinfo
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int deleteByPrimaryKey(Integer tradeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tradeinfo
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int insert(TbTradeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tradeinfo
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    TbTradeinfo selectByPrimaryKey(Integer tradeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tradeinfo
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    List<TbTradeinfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tradeinfo
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int updateByPrimaryKey(TbTradeinfo record);
}