package com.rrh.mapper.business;

import java.util.List;

import com.rrh.model.business.TbWhiteboardsComment;

public interface TbWhiteboardsCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_whiteboards_comment
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int deleteByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_whiteboards_comment
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int insert(TbWhiteboardsComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_whiteboards_comment
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    TbWhiteboardsComment selectByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_whiteboards_comment
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    List<TbWhiteboardsComment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_whiteboards_comment
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int updateByPrimaryKey(TbWhiteboardsComment record);
}