package com.rrh.mapper.business;

import java.util.List;

import com.rrh.model.business.TbWhiteboardsSendRecord;

public interface TbWhiteboardsSendRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_whiteboards_send_record
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int deleteByPrimaryKey(Integer wbRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_whiteboards_send_record
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int insert(TbWhiteboardsSendRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_whiteboards_send_record
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    TbWhiteboardsSendRecord selectByPrimaryKey(Integer wbRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_whiteboards_send_record
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    List<TbWhiteboardsSendRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_whiteboards_send_record
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int updateByPrimaryKey(TbWhiteboardsSendRecord record);
}