package com.rrh.mapper.business;

import java.util.List;

import com.rrh.model.business.WhiteboardsAttachment;

public interface WhiteboardsAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table whiteboards_attachment
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int deleteByPrimaryKey(Integer attachmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table whiteboards_attachment
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int insert(WhiteboardsAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table whiteboards_attachment
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    WhiteboardsAttachment selectByPrimaryKey(Integer attachmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table whiteboards_attachment
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    List<WhiteboardsAttachment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table whiteboards_attachment
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    int updateByPrimaryKey(WhiteboardsAttachment record);
}