package com.rrh.model.business;

import java.util.Date;

public class TbBusinessTaskExecute {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_task_execute.user_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_task_execute.task_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_task_execute.status
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_task_execute.add_time
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private Date addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_task_execute.user_id
     *
     * @return the value of tb_business_task_execute.user_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_task_execute.user_id
     *
     * @param userId the value for tb_business_task_execute.user_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_task_execute.task_id
     *
     * @return the value of tb_business_task_execute.task_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_task_execute.task_id
     *
     * @param taskId the value for tb_business_task_execute.task_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_task_execute.status
     *
     * @return the value of tb_business_task_execute.status
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_task_execute.status
     *
     * @param status the value for tb_business_task_execute.status
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_task_execute.add_time
     *
     * @return the value of tb_business_task_execute.add_time
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_task_execute.add_time
     *
     * @param addTime the value for tb_business_task_execute.add_time
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }
}