package com.rrh.model.business;

import java.util.Date;

public class TbBusinessKnowledgePraise {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_knowledge_praise.praise_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private Integer praiseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_knowledge_praise.user_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_knowledge_praise.source_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private Integer sourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_knowledge_praise.add_time
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_knowledge_praise.knowledge_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private Integer knowledgeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_knowledge_praise.praise_id
     *
     * @return the value of tb_business_knowledge_praise.praise_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public Integer getPraiseId() {
        return praiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_knowledge_praise.praise_id
     *
     * @param praiseId the value for tb_business_knowledge_praise.praise_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setPraiseId(Integer praiseId) {
        this.praiseId = praiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_knowledge_praise.user_id
     *
     * @return the value of tb_business_knowledge_praise.user_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_knowledge_praise.user_id
     *
     * @param userId the value for tb_business_knowledge_praise.user_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_knowledge_praise.source_id
     *
     * @return the value of tb_business_knowledge_praise.source_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public Integer getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_knowledge_praise.source_id
     *
     * @param sourceId the value for tb_business_knowledge_praise.source_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setSourceId(Integer sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_knowledge_praise.add_time
     *
     * @return the value of tb_business_knowledge_praise.add_time
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_knowledge_praise.add_time
     *
     * @param addTime the value for tb_business_knowledge_praise.add_time
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_knowledge_praise.knowledge_id
     *
     * @return the value of tb_business_knowledge_praise.knowledge_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public Integer getKnowledgeId() {
        return knowledgeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_knowledge_praise.knowledge_id
     *
     * @param knowledgeId the value for tb_business_knowledge_praise.knowledge_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setKnowledgeId(Integer knowledgeId) {
        this.knowledgeId = knowledgeId;
    }
}