package com.rrh.model.business;

public class TbBusinessGoodsPic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_goods_pic.pic_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private Integer picId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_goods_pic.pic_name
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private String picName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_goods_pic.goods_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_goods_pic.pic_path
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private String picPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_goods_pic.pic_id
     *
     * @return the value of tb_business_goods_pic.pic_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public Integer getPicId() {
        return picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_goods_pic.pic_id
     *
     * @param picId the value for tb_business_goods_pic.pic_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setPicId(Integer picId) {
        this.picId = picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_goods_pic.pic_name
     *
     * @return the value of tb_business_goods_pic.pic_name
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public String getPicName() {
        return picName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_goods_pic.pic_name
     *
     * @param picName the value for tb_business_goods_pic.pic_name
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setPicName(String picName) {
        this.picName = picName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_goods_pic.goods_id
     *
     * @return the value of tb_business_goods_pic.goods_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_goods_pic.goods_id
     *
     * @param goodsId the value for tb_business_goods_pic.goods_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_goods_pic.pic_path
     *
     * @return the value of tb_business_goods_pic.pic_path
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public String getPicPath() {
        return picPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_goods_pic.pic_path
     *
     * @param picPath the value for tb_business_goods_pic.pic_path
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setPicPath(String picPath) {
        this.picPath = picPath;
    }
}