package com.rrh.model.business;

import java.math.BigDecimal;

public class TbBusinessGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_goods.goods_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_goods.goods_name
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_goods.goods_price
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private BigDecimal goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_goods.goods_explain
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private String goodsExplain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_goods.goods_channel
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private String goodsChannel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_goods.goods_id
     *
     * @return the value of tb_business_goods.goods_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_goods.goods_id
     *
     * @param goodsId the value for tb_business_goods.goods_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_goods.goods_name
     *
     * @return the value of tb_business_goods.goods_name
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_goods.goods_name
     *
     * @param goodsName the value for tb_business_goods.goods_name
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_goods.goods_price
     *
     * @return the value of tb_business_goods.goods_price
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_goods.goods_price
     *
     * @param goodsPrice the value for tb_business_goods.goods_price
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_goods.goods_explain
     *
     * @return the value of tb_business_goods.goods_explain
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public String getGoodsExplain() {
        return goodsExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_goods.goods_explain
     *
     * @param goodsExplain the value for tb_business_goods.goods_explain
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setGoodsExplain(String goodsExplain) {
        this.goodsExplain = goodsExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_goods.goods_channel
     *
     * @return the value of tb_business_goods.goods_channel
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public String getGoodsChannel() {
        return goodsChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_goods.goods_channel
     *
     * @param goodsChannel the value for tb_business_goods.goods_channel
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setGoodsChannel(String goodsChannel) {
        this.goodsChannel = goodsChannel;
    }
}