package com.rrh.model.business;

import java.util.Date;

public class TbBusinessKnowledge {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_knowledge.knowledge_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private Integer knowledgeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_knowledge.title
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_knowledge.domain
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private String domain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_knowledge.knowledge_explain
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private String knowledgeExplain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_knowledge.create_time
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_knowledge.user_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_knowledge.praise_num
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private Integer praiseNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_knowledge.is_top
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private Integer isTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_knowledge.last_update_time
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_knowledge.business_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private Integer businessId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_knowledge.knowledge_id
     *
     * @return the value of tb_business_knowledge.knowledge_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public Integer getKnowledgeId() {
        return knowledgeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_knowledge.knowledge_id
     *
     * @param knowledgeId the value for tb_business_knowledge.knowledge_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setKnowledgeId(Integer knowledgeId) {
        this.knowledgeId = knowledgeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_knowledge.title
     *
     * @return the value of tb_business_knowledge.title
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_knowledge.title
     *
     * @param title the value for tb_business_knowledge.title
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_knowledge.domain
     *
     * @return the value of tb_business_knowledge.domain
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_knowledge.domain
     *
     * @param domain the value for tb_business_knowledge.domain
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setDomain(String domain) {
        this.domain = domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_knowledge.knowledge_explain
     *
     * @return the value of tb_business_knowledge.knowledge_explain
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public String getKnowledgeExplain() {
        return knowledgeExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_knowledge.knowledge_explain
     *
     * @param knowledgeExplain the value for tb_business_knowledge.knowledge_explain
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setKnowledgeExplain(String knowledgeExplain) {
        this.knowledgeExplain = knowledgeExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_knowledge.create_time
     *
     * @return the value of tb_business_knowledge.create_time
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_knowledge.create_time
     *
     * @param createTime the value for tb_business_knowledge.create_time
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_knowledge.user_id
     *
     * @return the value of tb_business_knowledge.user_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_knowledge.user_id
     *
     * @param userId the value for tb_business_knowledge.user_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_knowledge.praise_num
     *
     * @return the value of tb_business_knowledge.praise_num
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public Integer getPraiseNum() {
        return praiseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_knowledge.praise_num
     *
     * @param praiseNum the value for tb_business_knowledge.praise_num
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setPraiseNum(Integer praiseNum) {
        this.praiseNum = praiseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_knowledge.is_top
     *
     * @return the value of tb_business_knowledge.is_top
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public Integer getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_knowledge.is_top
     *
     * @param isTop the value for tb_business_knowledge.is_top
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setIsTop(Integer isTop) {
        this.isTop = isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_knowledge.last_update_time
     *
     * @return the value of tb_business_knowledge.last_update_time
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_knowledge.last_update_time
     *
     * @param lastUpdateTime the value for tb_business_knowledge.last_update_time
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_knowledge.business_id
     *
     * @return the value of tb_business_knowledge.business_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_knowledge.business_id
     *
     * @param businessId the value for tb_business_knowledge.business_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }
}