package com.rrh.model.business;

import java.util.Date;

public class TbBusinessWhiteboards {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_whiteboards.wb_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private Integer wbId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_whiteboards.goup_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private Integer goupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_whiteboards.send_time
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_whiteboards.msg_type
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private Integer msgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_whiteboards.attachment_explain
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private String attachmentExplain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_whiteboards.voice_name
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private String voiceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_whiteboards.business_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private Integer businessId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_whiteboards.wb_id
     *
     * @return the value of tb_business_whiteboards.wb_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public Integer getWbId() {
        return wbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_whiteboards.wb_id
     *
     * @param wbId the value for tb_business_whiteboards.wb_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setWbId(Integer wbId) {
        this.wbId = wbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_whiteboards.goup_id
     *
     * @return the value of tb_business_whiteboards.goup_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public Integer getGoupId() {
        return goupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_whiteboards.goup_id
     *
     * @param goupId the value for tb_business_whiteboards.goup_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setGoupId(Integer goupId) {
        this.goupId = goupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_whiteboards.send_time
     *
     * @return the value of tb_business_whiteboards.send_time
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_whiteboards.send_time
     *
     * @param sendTime the value for tb_business_whiteboards.send_time
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_whiteboards.msg_type
     *
     * @return the value of tb_business_whiteboards.msg_type
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public Integer getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_whiteboards.msg_type
     *
     * @param msgType the value for tb_business_whiteboards.msg_type
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setMsgType(Integer msgType) {
        this.msgType = msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_whiteboards.attachment_explain
     *
     * @return the value of tb_business_whiteboards.attachment_explain
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public String getAttachmentExplain() {
        return attachmentExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_whiteboards.attachment_explain
     *
     * @param attachmentExplain the value for tb_business_whiteboards.attachment_explain
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setAttachmentExplain(String attachmentExplain) {
        this.attachmentExplain = attachmentExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_whiteboards.voice_name
     *
     * @return the value of tb_business_whiteboards.voice_name
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public String getVoiceName() {
        return voiceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_whiteboards.voice_name
     *
     * @param voiceName the value for tb_business_whiteboards.voice_name
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setVoiceName(String voiceName) {
        this.voiceName = voiceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_whiteboards.business_id
     *
     * @return the value of tb_business_whiteboards.business_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_whiteboards.business_id
     *
     * @param businessId the value for tb_business_whiteboards.business_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }
}