package com.rrh.model.business;

import java.util.Date;

public class TbBusinessTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_task.task_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_task.task_explain
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private String taskExplain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_task.create_time
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_task.end_time
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_task.create_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private Integer createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_task.critical_level
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private Integer criticalLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_task.image_path
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private String imagePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_task.business_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private Integer businessId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_task.task_id
     *
     * @return the value of tb_business_task.task_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_task.task_id
     *
     * @param taskId the value for tb_business_task.task_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_task.task_explain
     *
     * @return the value of tb_business_task.task_explain
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public String getTaskExplain() {
        return taskExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_task.task_explain
     *
     * @param taskExplain the value for tb_business_task.task_explain
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setTaskExplain(String taskExplain) {
        this.taskExplain = taskExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_task.create_time
     *
     * @return the value of tb_business_task.create_time
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_task.create_time
     *
     * @param createTime the value for tb_business_task.create_time
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_task.end_time
     *
     * @return the value of tb_business_task.end_time
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_task.end_time
     *
     * @param endTime the value for tb_business_task.end_time
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_task.create_id
     *
     * @return the value of tb_business_task.create_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_task.create_id
     *
     * @param createId the value for tb_business_task.create_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_task.critical_level
     *
     * @return the value of tb_business_task.critical_level
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public Integer getCriticalLevel() {
        return criticalLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_task.critical_level
     *
     * @param criticalLevel the value for tb_business_task.critical_level
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setCriticalLevel(Integer criticalLevel) {
        this.criticalLevel = criticalLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_task.image_path
     *
     * @return the value of tb_business_task.image_path
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_task.image_path
     *
     * @param imagePath the value for tb_business_task.image_path
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_task.business_id
     *
     * @return the value of tb_business_task.business_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_task.business_id
     *
     * @param businessId the value for tb_business_task.business_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }
}