package com.rrh.model.business;

public class TbBusinessKnowledgeAttachment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_knowledge_attachment.attachment_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private Integer attachmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_knowledge_attachment.attachment_name
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private String attachmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_knowledge_attachment.knowledge_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private Integer knowledgeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_knowledge_attachment.attachment_type
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    private Integer attachmentType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_knowledge_attachment.attachment_id
     *
     * @return the value of tb_business_knowledge_attachment.attachment_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public Integer getAttachmentId() {
        return attachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_knowledge_attachment.attachment_id
     *
     * @param attachmentId the value for tb_business_knowledge_attachment.attachment_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setAttachmentId(Integer attachmentId) {
        this.attachmentId = attachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_knowledge_attachment.attachment_name
     *
     * @return the value of tb_business_knowledge_attachment.attachment_name
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public String getAttachmentName() {
        return attachmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_knowledge_attachment.attachment_name
     *
     * @param attachmentName the value for tb_business_knowledge_attachment.attachment_name
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setAttachmentName(String attachmentName) {
        this.attachmentName = attachmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_knowledge_attachment.knowledge_id
     *
     * @return the value of tb_business_knowledge_attachment.knowledge_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public Integer getKnowledgeId() {
        return knowledgeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_knowledge_attachment.knowledge_id
     *
     * @param knowledgeId the value for tb_business_knowledge_attachment.knowledge_id
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setKnowledgeId(Integer knowledgeId) {
        this.knowledgeId = knowledgeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_knowledge_attachment.attachment_type
     *
     * @return the value of tb_business_knowledge_attachment.attachment_type
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public Integer getAttachmentType() {
        return attachmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_knowledge_attachment.attachment_type
     *
     * @param attachmentType the value for tb_business_knowledge_attachment.attachment_type
     *
     * @mbggenerated Wed Nov 25 14:34:55 CST 2015
     */
    public void setAttachmentType(Integer attachmentType) {
        this.attachmentType = attachmentType;
    }
}