package com.rrh.model.business;

import java.util.Date;

public class TbBusiness {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business.business_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private Integer businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business.name
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business.taxes_code
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private String taxesCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business.trade_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private Integer tradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business.address
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business.domain
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private String domain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business.tel
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business.corporate_mobile
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private String corporateMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business.check_report
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private String checkReport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business.pass_certificate
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private String passCertificate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business.service_tel
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private String serviceTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business.complaint_tel
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private String complaintTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business.user_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business.lcd
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private Date lcd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business.business_id
     *
     * @return the value of tb_business.business_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business.business_id
     *
     * @param businessId the value for tb_business.business_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business.name
     *
     * @return the value of tb_business.name
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business.name
     *
     * @param name the value for tb_business.name
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business.taxes_code
     *
     * @return the value of tb_business.taxes_code
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public String getTaxesCode() {
        return taxesCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business.taxes_code
     *
     * @param taxesCode the value for tb_business.taxes_code
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setTaxesCode(String taxesCode) {
        this.taxesCode = taxesCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business.trade_id
     *
     * @return the value of tb_business.trade_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public Integer getTradeId() {
        return tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business.trade_id
     *
     * @param tradeId the value for tb_business.trade_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setTradeId(Integer tradeId) {
        this.tradeId = tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business.address
     *
     * @return the value of tb_business.address
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business.address
     *
     * @param address the value for tb_business.address
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business.domain
     *
     * @return the value of tb_business.domain
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business.domain
     *
     * @param domain the value for tb_business.domain
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setDomain(String domain) {
        this.domain = domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business.tel
     *
     * @return the value of tb_business.tel
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business.tel
     *
     * @param tel the value for tb_business.tel
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business.corporate_mobile
     *
     * @return the value of tb_business.corporate_mobile
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public String getCorporateMobile() {
        return corporateMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business.corporate_mobile
     *
     * @param corporateMobile the value for tb_business.corporate_mobile
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setCorporateMobile(String corporateMobile) {
        this.corporateMobile = corporateMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business.check_report
     *
     * @return the value of tb_business.check_report
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public String getCheckReport() {
        return checkReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business.check_report
     *
     * @param checkReport the value for tb_business.check_report
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setCheckReport(String checkReport) {
        this.checkReport = checkReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business.pass_certificate
     *
     * @return the value of tb_business.pass_certificate
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public String getPassCertificate() {
        return passCertificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business.pass_certificate
     *
     * @param passCertificate the value for tb_business.pass_certificate
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setPassCertificate(String passCertificate) {
        this.passCertificate = passCertificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business.service_tel
     *
     * @return the value of tb_business.service_tel
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public String getServiceTel() {
        return serviceTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business.service_tel
     *
     * @param serviceTel the value for tb_business.service_tel
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setServiceTel(String serviceTel) {
        this.serviceTel = serviceTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business.complaint_tel
     *
     * @return the value of tb_business.complaint_tel
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public String getComplaintTel() {
        return complaintTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business.complaint_tel
     *
     * @param complaintTel the value for tb_business.complaint_tel
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setComplaintTel(String complaintTel) {
        this.complaintTel = complaintTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business.user_id
     *
     * @return the value of tb_business.user_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business.user_id
     *
     * @param userId the value for tb_business.user_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business.lcd
     *
     * @return the value of tb_business.lcd
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public Date getLcd() {
        return lcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business.lcd
     *
     * @param lcd the value for tb_business.lcd
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setLcd(Date lcd) {
        this.lcd = lcd;
    }
}