package com.rrh.model.business;

public class TbDep {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dep.dep_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private Integer depId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dep.name
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dep.is_enabled
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private Boolean isEnabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dep.leading_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private Integer leadingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dep.parent_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private Integer parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dep.dep_id
     *
     * @return the value of tb_dep.dep_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public Integer getDepId() {
        return depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dep.dep_id
     *
     * @param depId the value for tb_dep.dep_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setDepId(Integer depId) {
        this.depId = depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dep.name
     *
     * @return the value of tb_dep.name
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dep.name
     *
     * @param name the value for tb_dep.name
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dep.is_enabled
     *
     * @return the value of tb_dep.is_enabled
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public Boolean getIsEnabled() {
        return isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dep.is_enabled
     *
     * @param isEnabled the value for tb_dep.is_enabled
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setIsEnabled(Boolean isEnabled) {
        this.isEnabled = isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dep.leading_id
     *
     * @return the value of tb_dep.leading_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public Integer getLeadingId() {
        return leadingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dep.leading_id
     *
     * @param leadingId the value for tb_dep.leading_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setLeadingId(Integer leadingId) {
        this.leadingId = leadingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dep.parent_id
     *
     * @return the value of tb_dep.parent_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dep.parent_id
     *
     * @param parentId the value for tb_dep.parent_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
}