package com.rrh.model.business;

public class TbTradeinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tradeinfo.trade_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private Integer tradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tradeinfo.trade_name
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private String tradeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tradeinfo.trade_id
     *
     * @return the value of tb_tradeinfo.trade_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public Integer getTradeId() {
        return tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tradeinfo.trade_id
     *
     * @param tradeId the value for tb_tradeinfo.trade_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setTradeId(Integer tradeId) {
        this.tradeId = tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tradeinfo.trade_name
     *
     * @return the value of tb_tradeinfo.trade_name
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public String getTradeName() {
        return tradeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tradeinfo.trade_name
     *
     * @param tradeName the value for tb_tradeinfo.trade_name
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setTradeName(String tradeName) {
        this.tradeName = tradeName;
    }
}