package com.rrh.model.business;

import java.util.Date;

public class TbWhiteboardsComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_whiteboards_comment.comment_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_whiteboards_comment.user_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_whiteboards_comment.content
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_whiteboards_comment.add_time
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_whiteboards_comment.praise_num
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private Integer praiseNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_whiteboards_comment.type
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_whiteboards_comment.rel_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private Integer relId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_whiteboards_comment.call_user_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private Integer callUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_whiteboards_comment.comment_id
     *
     * @return the value of tb_whiteboards_comment.comment_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_whiteboards_comment.comment_id
     *
     * @param commentId the value for tb_whiteboards_comment.comment_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_whiteboards_comment.user_id
     *
     * @return the value of tb_whiteboards_comment.user_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_whiteboards_comment.user_id
     *
     * @param userId the value for tb_whiteboards_comment.user_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_whiteboards_comment.content
     *
     * @return the value of tb_whiteboards_comment.content
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_whiteboards_comment.content
     *
     * @param content the value for tb_whiteboards_comment.content
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_whiteboards_comment.add_time
     *
     * @return the value of tb_whiteboards_comment.add_time
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_whiteboards_comment.add_time
     *
     * @param addTime the value for tb_whiteboards_comment.add_time
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_whiteboards_comment.praise_num
     *
     * @return the value of tb_whiteboards_comment.praise_num
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public Integer getPraiseNum() {
        return praiseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_whiteboards_comment.praise_num
     *
     * @param praiseNum the value for tb_whiteboards_comment.praise_num
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setPraiseNum(Integer praiseNum) {
        this.praiseNum = praiseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_whiteboards_comment.type
     *
     * @return the value of tb_whiteboards_comment.type
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_whiteboards_comment.type
     *
     * @param type the value for tb_whiteboards_comment.type
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_whiteboards_comment.rel_id
     *
     * @return the value of tb_whiteboards_comment.rel_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public Integer getRelId() {
        return relId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_whiteboards_comment.rel_id
     *
     * @param relId the value for tb_whiteboards_comment.rel_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setRelId(Integer relId) {
        this.relId = relId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_whiteboards_comment.call_user_id
     *
     * @return the value of tb_whiteboards_comment.call_user_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public Integer getCallUserId() {
        return callUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_whiteboards_comment.call_user_id
     *
     * @param callUserId the value for tb_whiteboards_comment.call_user_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setCallUserId(Integer callUserId) {
        this.callUserId = callUserId;
    }
}