package com.rrh.model.business;

import java.util.Date;

public class TbWhiteboardsSendRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_whiteboards_send_record.wb_record_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private Integer wbRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_whiteboards_send_record.user_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_whiteboards_send_record.whiteboards_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private Integer whiteboardsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_whiteboards_send_record.record_state
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private Integer recordState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_whiteboards_send_record.confirm_date
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    private Date confirmDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_whiteboards_send_record.wb_record_id
     *
     * @return the value of tb_whiteboards_send_record.wb_record_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public Integer getWbRecordId() {
        return wbRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_whiteboards_send_record.wb_record_id
     *
     * @param wbRecordId the value for tb_whiteboards_send_record.wb_record_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setWbRecordId(Integer wbRecordId) {
        this.wbRecordId = wbRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_whiteboards_send_record.user_id
     *
     * @return the value of tb_whiteboards_send_record.user_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_whiteboards_send_record.user_id
     *
     * @param userId the value for tb_whiteboards_send_record.user_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_whiteboards_send_record.whiteboards_id
     *
     * @return the value of tb_whiteboards_send_record.whiteboards_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public Integer getWhiteboardsId() {
        return whiteboardsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_whiteboards_send_record.whiteboards_id
     *
     * @param whiteboardsId the value for tb_whiteboards_send_record.whiteboards_id
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setWhiteboardsId(Integer whiteboardsId) {
        this.whiteboardsId = whiteboardsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_whiteboards_send_record.record_state
     *
     * @return the value of tb_whiteboards_send_record.record_state
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public Integer getRecordState() {
        return recordState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_whiteboards_send_record.record_state
     *
     * @param recordState the value for tb_whiteboards_send_record.record_state
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setRecordState(Integer recordState) {
        this.recordState = recordState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_whiteboards_send_record.confirm_date
     *
     * @return the value of tb_whiteboards_send_record.confirm_date
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public Date getConfirmDate() {
        return confirmDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_whiteboards_send_record.confirm_date
     *
     * @param confirmDate the value for tb_whiteboards_send_record.confirm_date
     *
     * @mbggenerated Wed Nov 18 23:19:15 CST 2015
     */
    public void setConfirmDate(Date confirmDate) {
        this.confirmDate = confirmDate;
    }
}