package com.rrh.mapper.user;

import java.util.List;

import com.rrh.model.user.TbBank;

public interface TbBankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bank
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    int deleteByPrimaryKey(Integer bankId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bank
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    int insert(TbBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bank
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    TbBank selectByPrimaryKey(Integer bankId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bank
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    List<TbBank> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bank
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    int updateByPrimaryKey(TbBank record);
}