package com.rrh.mapper.user;

import java.util.List;

import com.rrh.model.user.TbCity;

public interface TbCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_city
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    int deleteByPrimaryKey(Integer cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_city
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    int insert(TbCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_city
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    TbCity selectByPrimaryKey(Integer cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_city
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    List<TbCity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_city
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    int updateByPrimaryKey(TbCity record);
}