package com.rrh.mapper.user;

import java.util.List;

import com.rrh.model.user.TbDistrict;

public interface TbDistrictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_district
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    int deleteByPrimaryKey(Integer districtId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_district
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    int insert(TbDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_district
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    TbDistrict selectByPrimaryKey(Integer districtId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_district
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    List<TbDistrict> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_district
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    int updateByPrimaryKey(TbDistrict record);
}