package com.rrh.mapper.user;

import java.util.List;

import com.rrh.model.user.TbMobileSession;

public interface TbMobileSessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mobile_session
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    int deleteByPrimaryKey(Integer sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mobile_session
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    int insert(TbMobileSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mobile_session
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    TbMobileSession selectByPrimaryKey(Integer sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mobile_session
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    List<TbMobileSession> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mobile_session
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    int updateByPrimaryKey(TbMobileSession record);
    /**
     * 根据设备信息查询
     * @param appDeviceInfo
     * @return
     */
    TbMobileSession selectMobileSessionBySessionId(String appDeviceInfo);
}