package com.rrh.mapper.user;

import java.util.List;

import com.rrh.model.user.TbPayment;

public interface TbPaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_payment
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    int deleteByPrimaryKey(Integer paymentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_payment
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    int insert(TbPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_payment
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    TbPayment selectByPrimaryKey(Integer paymentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_payment
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    List<TbPayment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_payment
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    int updateByPrimaryKey(TbPayment record);
}