package com.rrh.mapper.user;

import java.util.List;

import com.rrh.model.user.TbPlaninfo;

public interface TbPlaninfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_planinfo
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    int deleteByPrimaryKey(Integer planId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_planinfo
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    int insert(TbPlaninfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_planinfo
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    TbPlaninfo selectByPrimaryKey(Integer planId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_planinfo
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    List<TbPlaninfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_planinfo
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    int updateByPrimaryKey(TbPlaninfo record);
}