package com.rrh.mapper.user;

import java.util.List;

import com.rrh.model.user.TbProvince;

public interface TbProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    int deleteByPrimaryKey(Integer provinceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    int insert(TbProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    TbProvince selectByPrimaryKey(Integer provinceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    List<TbProvince> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    int updateByPrimaryKey(TbProvince record);
}