package com.rrh.mapper.user;

import java.util.List;

import com.rrh.model.user.TbRegion;

public interface TbRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_region
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    int deleteByPrimaryKey(Integer regionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_region
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    int insert(TbRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_region
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    TbRegion selectByPrimaryKey(Integer regionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_region
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    List<TbRegion> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_region
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    int updateByPrimaryKey(TbRegion record);
}