package com.rrh.mapper.user;

import java.util.List;

import com.rrh.model.user.TbUsersBankCard;

public interface TbUsersBankCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users_bank_card
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    int deleteByPrimaryKey(Integer cardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users_bank_card
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    int insert(TbUsersBankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users_bank_card
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    TbUsersBankCard selectByPrimaryKey(Integer cardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users_bank_card
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    List<TbUsersBankCard> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users_bank_card
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    int updateByPrimaryKey(TbUsersBankCard record);
}