package com.rrh.mapper.user;

import java.util.List;

import com.rrh.model.user.TbUsersAccountLog;

public interface TbUsersAccountLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users_account_log
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    int deleteByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users_account_log
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    int insert(TbUsersAccountLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users_account_log
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    TbUsersAccountLog selectByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users_account_log
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    List<TbUsersAccountLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users_account_log
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    int updateByPrimaryKey(TbUsersAccountLog record);
}