package com.rrh.mapper.user;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.rrh.model.user.TbUsers;

public interface TbUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    int insert(TbUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    TbUsers selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    List<TbUsers> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    int updateByPrimaryKey(TbUsers record);
    
    /**
     * 选择性更新用户
     * @param record
     * @return
     */
    int updateByModelSelective(TbUsers record);
    /**
     * 选择性，多条件查询用户
     * @param record
     * @return
     */
    List<TbUsers> selectByModelSelective(TbUsers record);
   
    TbUsers selectUserByOpenId(TbUsers record);
    
    /**通过手机号码查询用户信息*/
    public TbUsers getByMobile(@Param(value="mobile") String mobile);
    /**统计手机号码用户数量*/
    public int countByMobile(String mobile);
    /**完善注册用户信息*/
    public int registerPerfectInfo(@Param(value="userId") int userId,@Param(value="nickName") String nickName,@Param(value="smallImg") String smallImg,@Param(value="bigImg") String bigImg,@Param(value="birthday") Date birthday,@Param(value="gender") int gender);
    
}