package com.rrh.mapper.user;

import java.util.List;

import com.rrh.model.user.TbUserInfo;

public interface TbUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_info
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_info
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    int insert(TbUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_info
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    TbUserInfo selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_info
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    List<TbUserInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_info
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    int updateByPrimaryKey(TbUserInfo record);
}