package com.rrh.mapper.user;

import java.util.HashMap;
import java.util.List;

import com.rrh.model.user.TbVerify;

public interface TbVerifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_verify
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    int deleteByPrimaryKey(Integer verifyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_verify
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    int insert(TbVerify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_verify
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    TbVerify selectByPrimaryKey(Integer verifyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_verify
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    List<TbVerify> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_verify
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    int updateByPrimaryKey(TbVerify record);
    /**
     * 生成验证码 存储过程
     * @param map
     * @return
     */
    int createVerify(HashMap<String,Object> map);
    
    /**
     * 校验验证码 存储过程
     * @param map
     * @return
     */
    int verifyCode(HashMap<String,Object> map);
}