package com.rrh.model.order;

import java.util.Date;

public class TbOrderinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderinfo.order_id
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderinfo.order_time
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    private Date orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderinfo.receiving_address
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    private String receivingAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderinfo.receiving_man
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    private String receivingMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderinfo.receiving_phone
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    private String receivingPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderinfo.goods_name
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderinfo.goods_id
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderinfo.order_remark
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    private String orderRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderinfo.order_state
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    private Integer orderState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderinfo.deliver_goods_date
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    private Date deliverGoodsDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderinfo.pay_state
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    private Integer payState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderinfo.pay_date
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    private Date payDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderinfo.order_id
     *
     * @return the value of tb_orderinfo.order_id
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderinfo.order_id
     *
     * @param orderId the value for tb_orderinfo.order_id
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderinfo.order_time
     *
     * @return the value of tb_orderinfo.order_time
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderinfo.order_time
     *
     * @param orderTime the value for tb_orderinfo.order_time
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderinfo.receiving_address
     *
     * @return the value of tb_orderinfo.receiving_address
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    public String getReceivingAddress() {
        return receivingAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderinfo.receiving_address
     *
     * @param receivingAddress the value for tb_orderinfo.receiving_address
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    public void setReceivingAddress(String receivingAddress) {
        this.receivingAddress = receivingAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderinfo.receiving_man
     *
     * @return the value of tb_orderinfo.receiving_man
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    public String getReceivingMan() {
        return receivingMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderinfo.receiving_man
     *
     * @param receivingMan the value for tb_orderinfo.receiving_man
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    public void setReceivingMan(String receivingMan) {
        this.receivingMan = receivingMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderinfo.receiving_phone
     *
     * @return the value of tb_orderinfo.receiving_phone
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    public String getReceivingPhone() {
        return receivingPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderinfo.receiving_phone
     *
     * @param receivingPhone the value for tb_orderinfo.receiving_phone
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    public void setReceivingPhone(String receivingPhone) {
        this.receivingPhone = receivingPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderinfo.goods_name
     *
     * @return the value of tb_orderinfo.goods_name
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderinfo.goods_name
     *
     * @param goodsName the value for tb_orderinfo.goods_name
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderinfo.goods_id
     *
     * @return the value of tb_orderinfo.goods_id
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderinfo.goods_id
     *
     * @param goodsId the value for tb_orderinfo.goods_id
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderinfo.order_remark
     *
     * @return the value of tb_orderinfo.order_remark
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    public String getOrderRemark() {
        return orderRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderinfo.order_remark
     *
     * @param orderRemark the value for tb_orderinfo.order_remark
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    public void setOrderRemark(String orderRemark) {
        this.orderRemark = orderRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderinfo.order_state
     *
     * @return the value of tb_orderinfo.order_state
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    public Integer getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderinfo.order_state
     *
     * @param orderState the value for tb_orderinfo.order_state
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    public void setOrderState(Integer orderState) {
        this.orderState = orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderinfo.deliver_goods_date
     *
     * @return the value of tb_orderinfo.deliver_goods_date
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    public Date getDeliverGoodsDate() {
        return deliverGoodsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderinfo.deliver_goods_date
     *
     * @param deliverGoodsDate the value for tb_orderinfo.deliver_goods_date
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    public void setDeliverGoodsDate(Date deliverGoodsDate) {
        this.deliverGoodsDate = deliverGoodsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderinfo.pay_state
     *
     * @return the value of tb_orderinfo.pay_state
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    public Integer getPayState() {
        return payState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderinfo.pay_state
     *
     * @param payState the value for tb_orderinfo.pay_state
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    public void setPayState(Integer payState) {
        this.payState = payState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderinfo.pay_date
     *
     * @return the value of tb_orderinfo.pay_date
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    public Date getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderinfo.pay_date
     *
     * @param payDate the value for tb_orderinfo.pay_date
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }
}