package com.rrh.model.order;

public class TbOrderPic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_pic.pic_id
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    private Integer picId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_pic.pic_name
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    private String picName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_pic.order_id
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    private Integer orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_pic.pic_id
     *
     * @return the value of tb_order_pic.pic_id
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    public Integer getPicId() {
        return picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_pic.pic_id
     *
     * @param picId the value for tb_order_pic.pic_id
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    public void setPicId(Integer picId) {
        this.picId = picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_pic.pic_name
     *
     * @return the value of tb_order_pic.pic_name
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    public String getPicName() {
        return picName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_pic.pic_name
     *
     * @param picName the value for tb_order_pic.pic_name
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    public void setPicName(String picName) {
        this.picName = picName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_pic.order_id
     *
     * @return the value of tb_order_pic.order_id
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_pic.order_id
     *
     * @param orderId the value for tb_order_pic.order_id
     *
     * @mbggenerated Wed Nov 18 23:29:07 CST 2015
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
}