package com.rrh.model.group;

import java.util.Date;

public class TbFriend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend.friend_id
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    private String friendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend.user_id
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend.nick_name
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend.relaty
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    private String relaty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend.status
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend.add_time
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    private Date addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend.friend_id
     *
     * @return the value of tb_friend.friend_id
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public String getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend.friend_id
     *
     * @param friendId the value for tb_friend.friend_id
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public void setFriendId(String friendId) {
        this.friendId = friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend.user_id
     *
     * @return the value of tb_friend.user_id
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend.user_id
     *
     * @param userId the value for tb_friend.user_id
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend.nick_name
     *
     * @return the value of tb_friend.nick_name
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend.nick_name
     *
     * @param nickName the value for tb_friend.nick_name
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend.relaty
     *
     * @return the value of tb_friend.relaty
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public String getRelaty() {
        return relaty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend.relaty
     *
     * @param relaty the value for tb_friend.relaty
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public void setRelaty(String relaty) {
        this.relaty = relaty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend.status
     *
     * @return the value of tb_friend.status
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend.status
     *
     * @param status the value for tb_friend.status
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend.add_time
     *
     * @return the value of tb_friend.add_time
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend.add_time
     *
     * @param addTime the value for tb_friend.add_time
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }
}