package com.rrh.model.group;

import java.util.Date;

public class TbGroupUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group_user.group_user_id
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    private Integer groupUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group_user.user_id
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group_user.group_id
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group_user.status
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group_user.add_time
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group_user.job_title
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    private String jobTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group_user.dep_id
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    private Integer depId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group_user.tel
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group_user.is_tel_show
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    private Integer isTelShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group_user.free_mode
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    private Integer freeMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group_user.set_top
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    private Integer setTop;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group_user.group_user_id
     *
     * @return the value of tb_group_user.group_user_id
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public Integer getGroupUserId() {
        return groupUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group_user.group_user_id
     *
     * @param groupUserId the value for tb_group_user.group_user_id
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public void setGroupUserId(Integer groupUserId) {
        this.groupUserId = groupUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group_user.user_id
     *
     * @return the value of tb_group_user.user_id
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group_user.user_id
     *
     * @param userId the value for tb_group_user.user_id
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group_user.group_id
     *
     * @return the value of tb_group_user.group_id
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group_user.group_id
     *
     * @param groupId the value for tb_group_user.group_id
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group_user.status
     *
     * @return the value of tb_group_user.status
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group_user.status
     *
     * @param status the value for tb_group_user.status
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group_user.add_time
     *
     * @return the value of tb_group_user.add_time
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group_user.add_time
     *
     * @param addTime the value for tb_group_user.add_time
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group_user.job_title
     *
     * @return the value of tb_group_user.job_title
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public String getJobTitle() {
        return jobTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group_user.job_title
     *
     * @param jobTitle the value for tb_group_user.job_title
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group_user.dep_id
     *
     * @return the value of tb_group_user.dep_id
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public Integer getDepId() {
        return depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group_user.dep_id
     *
     * @param depId the value for tb_group_user.dep_id
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public void setDepId(Integer depId) {
        this.depId = depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group_user.tel
     *
     * @return the value of tb_group_user.tel
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group_user.tel
     *
     * @param tel the value for tb_group_user.tel
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group_user.is_tel_show
     *
     * @return the value of tb_group_user.is_tel_show
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public Integer getIsTelShow() {
        return isTelShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group_user.is_tel_show
     *
     * @param isTelShow the value for tb_group_user.is_tel_show
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public void setIsTelShow(Integer isTelShow) {
        this.isTelShow = isTelShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group_user.free_mode
     *
     * @return the value of tb_group_user.free_mode
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public Integer getFreeMode() {
        return freeMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group_user.free_mode
     *
     * @param freeMode the value for tb_group_user.free_mode
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public void setFreeMode(Integer freeMode) {
        this.freeMode = freeMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group_user.set_top
     *
     * @return the value of tb_group_user.set_top
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public Integer getSetTop() {
        return setTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group_user.set_top
     *
     * @param setTop the value for tb_group_user.set_top
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public void setSetTop(Integer setTop) {
        this.setTop = setTop;
    }
}