package com.rrh.model.group;

import java.util.Date;

public class TbGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group.group_id
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group.name
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group.small_img
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    private String smallImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group.big_img
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    private String bigImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group.type
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group.business_id
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    private Integer businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group.user_id
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group.is_public
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    private String isPublic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group.bg_image
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    private String bgImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group.create_time
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group.parent_id
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group.qrcode
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    private String qrcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group.lcd
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    private Date lcd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group.group_id
     *
     * @return the value of tb_group.group_id
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group.group_id
     *
     * @param groupId the value for tb_group.group_id
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group.name
     *
     * @return the value of tb_group.name
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group.name
     *
     * @param name the value for tb_group.name
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group.small_img
     *
     * @return the value of tb_group.small_img
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public String getSmallImg() {
        return smallImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group.small_img
     *
     * @param smallImg the value for tb_group.small_img
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public void setSmallImg(String smallImg) {
        this.smallImg = smallImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group.big_img
     *
     * @return the value of tb_group.big_img
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public String getBigImg() {
        return bigImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group.big_img
     *
     * @param bigImg the value for tb_group.big_img
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public void setBigImg(String bigImg) {
        this.bigImg = bigImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group.type
     *
     * @return the value of tb_group.type
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group.type
     *
     * @param type the value for tb_group.type
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group.business_id
     *
     * @return the value of tb_group.business_id
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group.business_id
     *
     * @param businessId the value for tb_group.business_id
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group.user_id
     *
     * @return the value of tb_group.user_id
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group.user_id
     *
     * @param userId the value for tb_group.user_id
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group.is_public
     *
     * @return the value of tb_group.is_public
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public String getIsPublic() {
        return isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group.is_public
     *
     * @param isPublic the value for tb_group.is_public
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public void setIsPublic(String isPublic) {
        this.isPublic = isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group.bg_image
     *
     * @return the value of tb_group.bg_image
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public String getBgImage() {
        return bgImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group.bg_image
     *
     * @param bgImage the value for tb_group.bg_image
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public void setBgImage(String bgImage) {
        this.bgImage = bgImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group.create_time
     *
     * @return the value of tb_group.create_time
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group.create_time
     *
     * @param createTime the value for tb_group.create_time
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group.parent_id
     *
     * @return the value of tb_group.parent_id
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group.parent_id
     *
     * @param parentId the value for tb_group.parent_id
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group.qrcode
     *
     * @return the value of tb_group.qrcode
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public String getQrcode() {
        return qrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group.qrcode
     *
     * @param qrcode the value for tb_group.qrcode
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public void setQrcode(String qrcode) {
        this.qrcode = qrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group.lcd
     *
     * @return the value of tb_group.lcd
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public Date getLcd() {
        return lcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group.lcd
     *
     * @param lcd the value for tb_group.lcd
     *
     * @mbggenerated Wed Nov 18 23:25:37 CST 2015
     */
    public void setLcd(Date lcd) {
        this.lcd = lcd;
    }
}