package com.rrh.model.user;

public class TbBank {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bank.bank_id
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Integer bankId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bank.bank_name
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bank.bank_icon
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String bankIcon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bank.bank_id
     *
     * @return the value of tb_bank.bank_id
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Integer getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bank.bank_id
     *
     * @param bankId the value for tb_bank.bank_id
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setBankId(Integer bankId) {
        this.bankId = bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bank.bank_name
     *
     * @return the value of tb_bank.bank_name
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bank.bank_name
     *
     * @param bankName the value for tb_bank.bank_name
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bank.bank_icon
     *
     * @return the value of tb_bank.bank_icon
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getBankIcon() {
        return bankIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bank.bank_icon
     *
     * @param bankIcon the value for tb_bank.bank_icon
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setBankIcon(String bankIcon) {
        this.bankIcon = bankIcon;
    }
}