package com.rrh.model.user;

import java.util.Date;

public class TbCity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_city.city_id
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_city.city_name
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_city.zipcode
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    private String zipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_city.province_id
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    private Integer provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_city.add_date
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    private Date addDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_city.city_id
     *
     * @return the value of tb_city.city_id
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_city.city_id
     *
     * @param cityId the value for tb_city.city_id
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_city.city_name
     *
     * @return the value of tb_city.city_name
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_city.city_name
     *
     * @param cityName the value for tb_city.city_name
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_city.zipcode
     *
     * @return the value of tb_city.zipcode
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_city.zipcode
     *
     * @param zipcode the value for tb_city.zipcode
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_city.province_id
     *
     * @return the value of tb_city.province_id
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_city.province_id
     *
     * @param provinceId the value for tb_city.province_id
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_city.add_date
     *
     * @return the value of tb_city.add_date
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    public Date getAddDate() {
        return addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_city.add_date
     *
     * @param addDate the value for tb_city.add_date
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }
}