package com.rrh.model.user;

import java.util.Date;

public class TbDistrict {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_district.district_id
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    private Integer districtId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_district.district_name
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    private String districtName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_district.city_id
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_district.add_date
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    private Date addDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_district.district_id
     *
     * @return the value of tb_district.district_id
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    public Integer getDistrictId() {
        return districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_district.district_id
     *
     * @param districtId the value for tb_district.district_id
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    public void setDistrictId(Integer districtId) {
        this.districtId = districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_district.district_name
     *
     * @return the value of tb_district.district_name
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    public String getDistrictName() {
        return districtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_district.district_name
     *
     * @param districtName the value for tb_district.district_name
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    public void setDistrictName(String districtName) {
        this.districtName = districtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_district.city_id
     *
     * @return the value of tb_district.city_id
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_district.city_id
     *
     * @param cityId the value for tb_district.city_id
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_district.add_date
     *
     * @return the value of tb_district.add_date
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    public Date getAddDate() {
        return addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_district.add_date
     *
     * @param addDate the value for tb_district.add_date
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }
}