package com.rrh.model.user;

import java.util.Date;

public class TbMobileSession {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mobile_session.session_id
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    private Integer sessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mobile_session.login_token
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    private String loginToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mobile_session.app_deviceinfo
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    private String appDeviceInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mobile_session.app_system
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    private String appSystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mobile_session.app_channel
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    private String appChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mobile_session.last_login_time
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mobile_session.user_id
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mobile_session.session_id
     *
     * @return the value of tb_mobile_session.session_id
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public Integer getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mobile_session.session_id
     *
     * @param sessionId the value for tb_mobile_session.session_id
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public void setSessionId(Integer sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mobile_session.login_token
     *
     * @return the value of tb_mobile_session.login_token
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public String getLoginToken() {
        return loginToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mobile_session.login_token
     *
     * @param loginToken the value for tb_mobile_session.login_token
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public void setLoginToken(String loginToken) {
        this.loginToken = loginToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mobile_session.app_deviceinfo
     *
     * @return the value of tb_mobile_session.app_deviceinfo
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public String getAppDeviceInfo() {
        return appDeviceInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mobile_session.app_deviceinfo
     *
     * @param appDeviceinfo the value for tb_mobile_session.app_deviceinfo
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public void setAppDeviceInfo(String appDeviceInfo) {
        this.appDeviceInfo = appDeviceInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mobile_session.app_system
     *
     * @return the value of tb_mobile_session.app_system
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public String getAppSystem() {
        return appSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mobile_session.app_system
     *
     * @param appSystem the value for tb_mobile_session.app_system
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public void setAppSystem(String appSystem) {
        this.appSystem = appSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mobile_session.app_channel
     *
     * @return the value of tb_mobile_session.app_channel
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public String getAppChannel() {
        return appChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mobile_session.app_channel
     *
     * @param appChannel the value for tb_mobile_session.app_channel
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public void setAppChannel(String appChannel) {
        this.appChannel = appChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mobile_session.last_login_time
     *
     * @return the value of tb_mobile_session.last_login_time
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mobile_session.last_login_time
     *
     * @param lastLoginTime the value for tb_mobile_session.last_login_time
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mobile_session.user_id
     *
     * @return the value of tb_mobile_session.user_id
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mobile_session.user_id
     *
     * @param userId the value for tb_mobile_session.user_id
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}