package com.rrh.model.user;

public class TbPayment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_payment.payment_id
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Integer paymentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_payment.code
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_payment.name
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_payment.payment_explain
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String paymentExplain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_payment.is_enabled
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Byte isEnabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_payment.is_online
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Byte isOnline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_payment.order_sort
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Integer orderSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_payment.config
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String config;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_payment.icon
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String icon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_payment.payment_id
     *
     * @return the value of tb_payment.payment_id
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Integer getPaymentId() {
        return paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_payment.payment_id
     *
     * @param paymentId the value for tb_payment.payment_id
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setPaymentId(Integer paymentId) {
        this.paymentId = paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_payment.code
     *
     * @return the value of tb_payment.code
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_payment.code
     *
     * @param code the value for tb_payment.code
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_payment.name
     *
     * @return the value of tb_payment.name
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_payment.name
     *
     * @param name the value for tb_payment.name
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_payment.payment_explain
     *
     * @return the value of tb_payment.payment_explain
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getPaymentExplain() {
        return paymentExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_payment.payment_explain
     *
     * @param paymentExplain the value for tb_payment.payment_explain
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setPaymentExplain(String paymentExplain) {
        this.paymentExplain = paymentExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_payment.is_enabled
     *
     * @return the value of tb_payment.is_enabled
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Byte getIsEnabled() {
        return isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_payment.is_enabled
     *
     * @param isEnabled the value for tb_payment.is_enabled
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setIsEnabled(Byte isEnabled) {
        this.isEnabled = isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_payment.is_online
     *
     * @return the value of tb_payment.is_online
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Byte getIsOnline() {
        return isOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_payment.is_online
     *
     * @param isOnline the value for tb_payment.is_online
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setIsOnline(Byte isOnline) {
        this.isOnline = isOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_payment.order_sort
     *
     * @return the value of tb_payment.order_sort
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Integer getOrderSort() {
        return orderSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_payment.order_sort
     *
     * @param orderSort the value for tb_payment.order_sort
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setOrderSort(Integer orderSort) {
        this.orderSort = orderSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_payment.config
     *
     * @return the value of tb_payment.config
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getConfig() {
        return config;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_payment.config
     *
     * @param config the value for tb_payment.config
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setConfig(String config) {
        this.config = config;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_payment.icon
     *
     * @return the value of tb_payment.icon
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_payment.icon
     *
     * @param icon the value for tb_payment.icon
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }
}