package com.rrh.model.user;

import java.util.Date;

public class TbPlaninfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_planinfo.plan_id
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Integer planId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_planinfo.plan_type
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Integer planType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_planinfo.plan_begin_date
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Date planBeginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_planinfo.plan_over_date
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Date planOverDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_planinfo.user_id
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_planinfo.plan_explain
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String planExplain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_planinfo.plan_supplement
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String planSupplement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_planinfo.plan_createtime
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Date planCreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_planinfo.lcd
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Date lcd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_planinfo.plan_id
     *
     * @return the value of tb_planinfo.plan_id
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Integer getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_planinfo.plan_id
     *
     * @param planId the value for tb_planinfo.plan_id
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_planinfo.plan_type
     *
     * @return the value of tb_planinfo.plan_type
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Integer getPlanType() {
        return planType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_planinfo.plan_type
     *
     * @param planType the value for tb_planinfo.plan_type
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setPlanType(Integer planType) {
        this.planType = planType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_planinfo.plan_begin_date
     *
     * @return the value of tb_planinfo.plan_begin_date
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Date getPlanBeginDate() {
        return planBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_planinfo.plan_begin_date
     *
     * @param planBeginDate the value for tb_planinfo.plan_begin_date
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setPlanBeginDate(Date planBeginDate) {
        this.planBeginDate = planBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_planinfo.plan_over_date
     *
     * @return the value of tb_planinfo.plan_over_date
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Date getPlanOverDate() {
        return planOverDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_planinfo.plan_over_date
     *
     * @param planOverDate the value for tb_planinfo.plan_over_date
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setPlanOverDate(Date planOverDate) {
        this.planOverDate = planOverDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_planinfo.user_id
     *
     * @return the value of tb_planinfo.user_id
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_planinfo.user_id
     *
     * @param userId the value for tb_planinfo.user_id
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_planinfo.plan_explain
     *
     * @return the value of tb_planinfo.plan_explain
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getPlanExplain() {
        return planExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_planinfo.plan_explain
     *
     * @param planExplain the value for tb_planinfo.plan_explain
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setPlanExplain(String planExplain) {
        this.planExplain = planExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_planinfo.plan_supplement
     *
     * @return the value of tb_planinfo.plan_supplement
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getPlanSupplement() {
        return planSupplement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_planinfo.plan_supplement
     *
     * @param planSupplement the value for tb_planinfo.plan_supplement
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setPlanSupplement(String planSupplement) {
        this.planSupplement = planSupplement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_planinfo.plan_createtime
     *
     * @return the value of tb_planinfo.plan_createtime
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Date getPlanCreatetime() {
        return planCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_planinfo.plan_createtime
     *
     * @param planCreatetime the value for tb_planinfo.plan_createtime
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setPlanCreatetime(Date planCreatetime) {
        this.planCreatetime = planCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_planinfo.lcd
     *
     * @return the value of tb_planinfo.lcd
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Date getLcd() {
        return lcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_planinfo.lcd
     *
     * @param lcd the value for tb_planinfo.lcd
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setLcd(Date lcd) {
        this.lcd = lcd;
    }
}