package com.rrh.model.user;

import java.util.Date;

public class TbProvince {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_province.province_id
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    private Integer provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_province.province_name
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_province.add_date
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    private Date addDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_province.province_id
     *
     * @return the value of tb_province.province_id
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_province.province_id
     *
     * @param provinceId the value for tb_province.province_id
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_province.province_name
     *
     * @return the value of tb_province.province_name
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_province.province_name
     *
     * @param provinceName the value for tb_province.province_name
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_province.add_date
     *
     * @return the value of tb_province.add_date
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    public Date getAddDate() {
        return addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_province.add_date
     *
     * @param addDate the value for tb_province.add_date
     *
     * @mbggenerated Sat Nov 21 13:44:45 CST 2015
     */
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }
}