package com.rrh.model.user;

public class TbRegion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_region.region_id
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Integer regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_region.region_name
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String regionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_region.parent_id
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_region.region_type
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Integer regionType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_region.region_id
     *
     * @return the value of tb_region.region_id
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Integer getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_region.region_id
     *
     * @param regionId the value for tb_region.region_id
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_region.region_name
     *
     * @return the value of tb_region.region_name
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_region.region_name
     *
     * @param regionName the value for tb_region.region_name
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_region.parent_id
     *
     * @return the value of tb_region.parent_id
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_region.parent_id
     *
     * @param parentId the value for tb_region.parent_id
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_region.region_type
     *
     * @return the value of tb_region.region_type
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Integer getRegionType() {
        return regionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_region.region_type
     *
     * @param regionType the value for tb_region.region_type
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setRegionType(Integer regionType) {
        this.regionType = regionType;
    }
}