package com.rrh.model.user;

public class TbUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.user_id
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.goods_at
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String goodsAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.place
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String place;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.food
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String food;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.stature
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String stature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.weight
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.emotion
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Integer emotion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.sports
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String sports;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.user_id
     *
     * @return the value of tb_user_info.user_id
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.user_id
     *
     * @param userId the value for tb_user_info.user_id
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.goods_at
     *
     * @return the value of tb_user_info.goods_at
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getGoodsAt() {
        return goodsAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.goods_at
     *
     * @param goodsAt the value for tb_user_info.goods_at
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setGoodsAt(String goodsAt) {
        this.goodsAt = goodsAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.place
     *
     * @return the value of tb_user_info.place
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.place
     *
     * @param place the value for tb_user_info.place
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setPlace(String place) {
        this.place = place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.food
     *
     * @return the value of tb_user_info.food
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getFood() {
        return food;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.food
     *
     * @param food the value for tb_user_info.food
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setFood(String food) {
        this.food = food;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.stature
     *
     * @return the value of tb_user_info.stature
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getStature() {
        return stature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.stature
     *
     * @param stature the value for tb_user_info.stature
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setStature(String stature) {
        this.stature = stature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.weight
     *
     * @return the value of tb_user_info.weight
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.weight
     *
     * @param weight the value for tb_user_info.weight
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setWeight(String weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.emotion
     *
     * @return the value of tb_user_info.emotion
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Integer getEmotion() {
        return emotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.emotion
     *
     * @param emotion the value for tb_user_info.emotion
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setEmotion(Integer emotion) {
        this.emotion = emotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.sports
     *
     * @return the value of tb_user_info.sports
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getSports() {
        return sports;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.sports
     *
     * @param sports the value for tb_user_info.sports
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setSports(String sports) {
        this.sports = sports;
    }
}