package com.rrh.model.user;

public class TbUsersBankCard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users_bank_card.card_id
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    private Integer cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users_bank_card.card_num
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    private String cardNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users_bank_card.bank_id
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    private Integer bankId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users_bank_card.uset_id
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    private Integer usetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users_bank_card.true_name
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    private String trueName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users_bank_card.card_id
     *
     * @return the value of tb_users_bank_card.card_id
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public Integer getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users_bank_card.card_id
     *
     * @param cardId the value for tb_users_bank_card.card_id
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public void setCardId(Integer cardId) {
        this.cardId = cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users_bank_card.card_num
     *
     * @return the value of tb_users_bank_card.card_num
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public String getCardNum() {
        return cardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users_bank_card.card_num
     *
     * @param cardNum the value for tb_users_bank_card.card_num
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public void setCardNum(String cardNum) {
        this.cardNum = cardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users_bank_card.bank_id
     *
     * @return the value of tb_users_bank_card.bank_id
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public Integer getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users_bank_card.bank_id
     *
     * @param bankId the value for tb_users_bank_card.bank_id
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public void setBankId(Integer bankId) {
        this.bankId = bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users_bank_card.uset_id
     *
     * @return the value of tb_users_bank_card.uset_id
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public Integer getUsetId() {
        return usetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users_bank_card.uset_id
     *
     * @param usetId the value for tb_users_bank_card.uset_id
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public void setUsetId(Integer usetId) {
        this.usetId = usetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users_bank_card.true_name
     *
     * @return the value of tb_users_bank_card.true_name
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public String getTrueName() {
        return trueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users_bank_card.true_name
     *
     * @param trueName the value for tb_users_bank_card.true_name
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public void setTrueName(String trueName) {
        this.trueName = trueName;
    }
}