package com.rrh.model.user;

import java.math.BigDecimal;
import java.util.Date;

public class TbUsers {
	private String appSystem;
	private String appDeviceInfo;
	private String appChannel;
	private String loginToken;
    public String getAppSystem() {
		return appSystem;
	}

	public void setAppSystem(String appSystem) {
		this.appSystem = appSystem;
	}

	public String getAppDeviceInfo() {
		return appDeviceInfo;
	}

	public void setAppDeviceInfo(String appDeviceInfo) {
		this.appDeviceInfo = appDeviceInfo;
	}

	public String getAppChannel() {
		return appChannel;
	}

	public void setAppChannel(String appChannel) {
		this.appChannel = appChannel;
	}

	public String getLoginToken() {
		return loginToken;
	}

	public void setLoginToken(String loginToken) {
		this.loginToken = loginToken;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.user_id
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.user_name
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.mobile
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.password
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.true_name
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String trueName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.nick_name
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.money
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private BigDecimal money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.gender
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.birthday
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.small_img
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String smallImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.big_img
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String bigImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.reg_time
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Date regTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.last_time
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Date lastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.login_count
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Integer loginCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.is_certification
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Boolean isCertification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.province
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Integer province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.city
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Integer city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.area
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Integer area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.id_card
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.id_card_image
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String idCardImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.business_name
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String businessName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.business_desc
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String businessDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.business_traffic
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String businessTraffic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.business_address
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String businessAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.business_domain
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String businessDomain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.business_weixin
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String businessWeixin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.details
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String details;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.signature
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String signature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.email
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.pay_password
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String payPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.contacts_password
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String contactsPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.lcd
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Date lcd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.user_id
     *
     * @return the value of tb_users.user_id
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.user_id
     *
     * @param userId the value for tb_users.user_id
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.user_name
     *
     * @return the value of tb_users.user_name
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.user_name
     *
     * @param userName the value for tb_users.user_name
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.mobile
     *
     * @return the value of tb_users.mobile
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.mobile
     *
     * @param mobile the value for tb_users.mobile
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.password
     *
     * @return the value of tb_users.password
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.password
     *
     * @param password the value for tb_users.password
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.true_name
     *
     * @return the value of tb_users.true_name
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getTrueName() {
        return trueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.true_name
     *
     * @param trueName the value for tb_users.true_name
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setTrueName(String trueName) {
        this.trueName = trueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.nick_name
     *
     * @return the value of tb_users.nick_name
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.nick_name
     *
     * @param nickName the value for tb_users.nick_name
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.money
     *
     * @return the value of tb_users.money
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.money
     *
     * @param money the value for tb_users.money
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.gender
     *
     * @return the value of tb_users.gender
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.gender
     *
     * @param gender the value for tb_users.gender
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.birthday
     *
     * @return the value of tb_users.birthday
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.birthday
     *
     * @param birthday the value for tb_users.birthday
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.small_img
     *
     * @return the value of tb_users.small_img
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getSmallImg() {
        return smallImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.small_img
     *
     * @param smallImg the value for tb_users.small_img
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setSmallImg(String smallImg) {
        this.smallImg = smallImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.big_img
     *
     * @return the value of tb_users.big_img
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getBigImg() {
        return bigImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.big_img
     *
     * @param bigImg the value for tb_users.big_img
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setBigImg(String bigImg) {
        this.bigImg = bigImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.reg_time
     *
     * @return the value of tb_users.reg_time
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.reg_time
     *
     * @param regTime the value for tb_users.reg_time
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.last_time
     *
     * @return the value of tb_users.last_time
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.last_time
     *
     * @param lastTime the value for tb_users.last_time
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.login_count
     *
     * @return the value of tb_users.login_count
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Integer getLoginCount() {
        return loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.login_count
     *
     * @param loginCount the value for tb_users.login_count
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setLoginCount(Integer loginCount) {
        this.loginCount = loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.is_certification
     *
     * @return the value of tb_users.is_certification
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Boolean getIsCertification() {
        return isCertification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.is_certification
     *
     * @param isCertification the value for tb_users.is_certification
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setIsCertification(Boolean isCertification) {
        this.isCertification = isCertification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.province
     *
     * @return the value of tb_users.province
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Integer getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.province
     *
     * @param province the value for tb_users.province
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setProvince(Integer province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.city
     *
     * @return the value of tb_users.city
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.city
     *
     * @param city the value for tb_users.city
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.area
     *
     * @return the value of tb_users.area
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Integer getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.area
     *
     * @param area the value for tb_users.area
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setArea(Integer area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.id_card
     *
     * @return the value of tb_users.id_card
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.id_card
     *
     * @param idCard the value for tb_users.id_card
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.id_card_image
     *
     * @return the value of tb_users.id_card_image
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getIdCardImage() {
        return idCardImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.id_card_image
     *
     * @param idCardImage the value for tb_users.id_card_image
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setIdCardImage(String idCardImage) {
        this.idCardImage = idCardImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.business_name
     *
     * @return the value of tb_users.business_name
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.business_name
     *
     * @param businessName the value for tb_users.business_name
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setBusinessName(String businessName) {
        this.businessName = businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.business_desc
     *
     * @return the value of tb_users.business_desc
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getBusinessDesc() {
        return businessDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.business_desc
     *
     * @param businessDesc the value for tb_users.business_desc
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setBusinessDesc(String businessDesc) {
        this.businessDesc = businessDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.business_traffic
     *
     * @return the value of tb_users.business_traffic
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getBusinessTraffic() {
        return businessTraffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.business_traffic
     *
     * @param businessTraffic the value for tb_users.business_traffic
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setBusinessTraffic(String businessTraffic) {
        this.businessTraffic = businessTraffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.business_address
     *
     * @return the value of tb_users.business_address
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getBusinessAddress() {
        return businessAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.business_address
     *
     * @param businessAddress the value for tb_users.business_address
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setBusinessAddress(String businessAddress) {
        this.businessAddress = businessAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.business_domain
     *
     * @return the value of tb_users.business_domain
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getBusinessDomain() {
        return businessDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.business_domain
     *
     * @param businessDomain the value for tb_users.business_domain
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setBusinessDomain(String businessDomain) {
        this.businessDomain = businessDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.business_weixin
     *
     * @return the value of tb_users.business_weixin
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getBusinessWeixin() {
        return businessWeixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.business_weixin
     *
     * @param businessWeixin the value for tb_users.business_weixin
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setBusinessWeixin(String businessWeixin) {
        this.businessWeixin = businessWeixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.details
     *
     * @return the value of tb_users.details
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.details
     *
     * @param details the value for tb_users.details
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setDetails(String details) {
        this.details = details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.signature
     *
     * @return the value of tb_users.signature
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.signature
     *
     * @param signature the value for tb_users.signature
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setSignature(String signature) {
        this.signature = signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.email
     *
     * @return the value of tb_users.email
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.email
     *
     * @param email the value for tb_users.email
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.pay_password
     *
     * @return the value of tb_users.pay_password
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getPayPassword() {
        return payPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.pay_password
     *
     * @param payPassword the value for tb_users.pay_password
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setPayPassword(String payPassword) {
        this.payPassword = payPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.contacts_password
     *
     * @return the value of tb_users.contacts_password
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getContactsPassword() {
        return contactsPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.contacts_password
     *
     * @param contactsPassword the value for tb_users.contacts_password
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setContactsPassword(String contactsPassword) {
        this.contactsPassword = contactsPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.lcd
     *
     * @return the value of tb_users.lcd
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Date getLcd() {
        return lcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.lcd
     *
     * @param lcd the value for tb_users.lcd
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setLcd(Date lcd) {
        this.lcd = lcd;
    }
}