package com.rrh.model.user;

import java.util.Date;

public class TbUsersAccountLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users_account_log.log_id
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    private Integer logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users_account_log.user_id
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users_account_log.money
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    private Float money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users_account_log.user_money
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    private Float userMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users_account_log.point
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    private Integer point;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users_account_log.user_point
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    private Integer userPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users_account_log.change_time
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    private Date changeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users_account_log.change_desc
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    private String changeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users_account_log.change_type
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    private String changeType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users_account_log.log_id
     *
     * @return the value of tb_users_account_log.log_id
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users_account_log.log_id
     *
     * @param logId the value for tb_users_account_log.log_id
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users_account_log.user_id
     *
     * @return the value of tb_users_account_log.user_id
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users_account_log.user_id
     *
     * @param userId the value for tb_users_account_log.user_id
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users_account_log.money
     *
     * @return the value of tb_users_account_log.money
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public Float getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users_account_log.money
     *
     * @param money the value for tb_users_account_log.money
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public void setMoney(Float money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users_account_log.user_money
     *
     * @return the value of tb_users_account_log.user_money
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public Float getUserMoney() {
        return userMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users_account_log.user_money
     *
     * @param userMoney the value for tb_users_account_log.user_money
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public void setUserMoney(Float userMoney) {
        this.userMoney = userMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users_account_log.point
     *
     * @return the value of tb_users_account_log.point
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users_account_log.point
     *
     * @param point the value for tb_users_account_log.point
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public void setPoint(Integer point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users_account_log.user_point
     *
     * @return the value of tb_users_account_log.user_point
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public Integer getUserPoint() {
        return userPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users_account_log.user_point
     *
     * @param userPoint the value for tb_users_account_log.user_point
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public void setUserPoint(Integer userPoint) {
        this.userPoint = userPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users_account_log.change_time
     *
     * @return the value of tb_users_account_log.change_time
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public Date getChangeTime() {
        return changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users_account_log.change_time
     *
     * @param changeTime the value for tb_users_account_log.change_time
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public void setChangeTime(Date changeTime) {
        this.changeTime = changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users_account_log.change_desc
     *
     * @return the value of tb_users_account_log.change_desc
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public String getChangeDesc() {
        return changeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users_account_log.change_desc
     *
     * @param changeDesc the value for tb_users_account_log.change_desc
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public void setChangeDesc(String changeDesc) {
        this.changeDesc = changeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users_account_log.change_type
     *
     * @return the value of tb_users_account_log.change_type
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public String getChangeType() {
        return changeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users_account_log.change_type
     *
     * @param changeType the value for tb_users_account_log.change_type
     *
     * @mbggenerated Wed Nov 25 14:34:16 CST 2015
     */
    public void setChangeType(String changeType) {
        this.changeType = changeType;
    }
}