package com.rrh.model.user;

import java.util.Date;

public class TbVerify {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_verify.verify_id
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Integer verifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_verify.mobile
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_verify.verify_code
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private String verifyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_verify.add_time
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_verify.verify_type
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Integer verifyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_verify.request_count
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Integer requestCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_verify.isused
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    private Integer isused;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_verify.verify_id
     *
     * @return the value of tb_verify.verify_id
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Integer getVerifyId() {
        return verifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_verify.verify_id
     *
     * @param verifyId the value for tb_verify.verify_id
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setVerifyId(Integer verifyId) {
        this.verifyId = verifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_verify.mobile
     *
     * @return the value of tb_verify.mobile
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_verify.mobile
     *
     * @param mobile the value for tb_verify.mobile
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_verify.verify_code
     *
     * @return the value of tb_verify.verify_code
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public String getVerifyCode() {
        return verifyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_verify.verify_code
     *
     * @param verifyCode the value for tb_verify.verify_code
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setVerifyCode(String verifyCode) {
        this.verifyCode = verifyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_verify.add_time
     *
     * @return the value of tb_verify.add_time
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_verify.add_time
     *
     * @param addTime the value for tb_verify.add_time
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_verify.verify_type
     *
     * @return the value of tb_verify.verify_type
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Integer getVerifyType() {
        return verifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_verify.verify_type
     *
     * @param verifyType the value for tb_verify.verify_type
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setVerifyType(Integer verifyType) {
        this.verifyType = verifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_verify.request_count
     *
     * @return the value of tb_verify.request_count
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Integer getRequestCount() {
        return requestCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_verify.request_count
     *
     * @param requestCount the value for tb_verify.request_count
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setRequestCount(Integer requestCount) {
        this.requestCount = requestCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_verify.isused
     *
     * @return the value of tb_verify.isused
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public Integer getIsused() {
        return isused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_verify.isused
     *
     * @param isused the value for tb_verify.isused
     *
     * @mbggenerated Wed Nov 18 23:31:15 CST 2015
     */
    public void setIsused(Integer isused) {
        this.isused = isused;
    }
}